apiVersion: v1
kind: ServiceAccount
metadata:
  name: queueflow

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queueflow-api
  template:
    metadata:
      labels:
        app: queueflow-api
    spec:
      serviceAccountName: queueflow
      terminationGracePeriodSeconds: 60
      containers:
        - name: api
          image: queueflow-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: queueflow-config
            - secretRef:
                name: queueflow-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: queueflow-api
spec:
  selector:
    app: queueflow-api
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queueflow-worker
  template:
    metadata:
      labels:
        app: queueflow-worker
    spec:
      serviceAccountName: queueflow
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: queueflow-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: queueflow-config
            - secretRef:
                name: queueflow-secrets
          env:
            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
