apiVersion: v1
kind: ConfigMap
metadata:
  name: queueflow-config
data:
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/819379976838/queueflow-jobs
  S3_RESULTS_BUCKET: queueflow-results-819379976838-us-east-1
  WORKER_CPU_CAPACITY: "4"
  WORKER_MEMORY_MB: "8192"
  WORKER_GPU_CAPACITY: "0"

---
apiVersion: v1
kind: Secret
metadata:
  name: queueflow-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://queueflow:queueflow@host.docker.internal:5433/queueflow

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queueflow-api
  template:
    metadata:
      labels:
        app: queueflow-api
    spec:
      containers:
        - name: api
          image: queueflow-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: queueflow-config
            - secretRef:
                name: queueflow-secrets

          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /root/.aws/credentials
            - name: AWS_CONFIG_FILE
              value: /root/.aws/config

          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: aws-credentials
          hostPath:
            path: /Users/chanakyag/.aws
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: queueflow-api
spec:
  selector:
    app: queueflow-api
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queueflow-worker
  template:
    metadata:
      labels:
        app: queueflow-worker
    spec:
      containers:
        - name: worker
          image: queueflow-worker:local
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: queueflow-config
            - secretRef:
                name: queueflow-secrets

          env:
            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /root/.aws/credentials

            - name: AWS_CONFIG_FILE
              value: /root/.aws/config

          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

      volumes:
        - name: aws-credentials
          hostPath:
            path: /Users/chanakyag/.aws
            type: Directory